(function() {var implementors = {};
implementors["twitch_api2"] = [{"text":"impl Eq for CommercialLength","synthetic":false,"types":[]},{"text":"impl Eq for AutoGenerated","synthetic":false,"types":[]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()